version: 2

defaults: &defaults

  working_directory:  ~/DiceRoller
  docker:
  - image: circleci/android:api-29
  environment:
    JVM_OPTS: -Xmx3200m
    BUNDLER_VERSION: 2.0.1

  steps:
  - checkout
  - restore_cache:
      key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  - run:
      name: Install fastlane
      command: bundle update
  - save_cache:
      paths:
      - ~/.gradle
      key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  - run:
      name: Fastlane
      command: bundle exec fastlane $FASTLANE_LANE
      no_output_timeout: 60m
jobs:
  deploy-internal:
    environment:
      FASTLANE_LANE: dev
    <<: *defaults

workflows:
  version: 2
  deploy-internal-build:
    jobs:
    - deploy-internal:
        filters:
          tags:
            only: /release.*/
          branches:
            ignore: /.*/

