version: 2

defaults: &defaults

  working_directory:  ~/DiceRoller
  docker:
  - image: circleci/android:api-29
  environment:
    JVM_OPTS: -Xmx3200m
  steps:
  - checkout
  - restore_cache:
      key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  - run:
      name: Install fastlane
      command: bundle update
  - run:
      name: Install Firebase Tools
      command: fastlane add_plugin firebase_app_distribution
  - run:
      name: Check Firebase
      command: which firebase
  - run:
      name: Download Dependencies
      command: ./gradlew androidDependencies
  - save_cache:
      paths:
      - ~/.gradle
      key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  - run:
      name: Fastlane
      command: bundle exec fastlane $FASTLANE_LANE
      no_output_timeout: 60m
jobs:
  deploy-internal:
    environment:
      FASTLANE_LANE: internal
    <<: *defaults

workflows:
  version: 2
  deploy-internal-build:
    jobs:
    - deploy-internal

