# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Submit a new Tester build to firebase app distribution.
  lane :internal do
        gradle(task: 'clean')
  end

  # You can define as many lanes as you want

    after_all do |lane|
    end

    error do |lane, exception|
    end
end
