opt_out_usage
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

   desc "Submit a new internal Build to Crashlytics Beta"
    lane :internal do
    gradle(task:"clean")
      gradle(
        task: "assemble",
        flavor: "Dev",
        build_type: "Debug"
      )
    # tag = "release-internal-v1.0.13"
    # add_git_tag(tag: tag)
    # push_to_git_remote
    end

end
