# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :dev do
        gradle(
          task: "assemble",
          flavor: "Dev",
          build_type: "Debug"
        )
        firebasePath = sh("which firebase")
        firebaseDirectory = sh("dirname #{firebasePath}")
        firebase_app_distribution(
            app: "1:159125261893:android:7a49ecce6208337bd21d2c",
            testers: "mail.nithinp@gmail.com",
            release_notes: "Lots of amazing new features to test out!",
            firebase_cli_path: "#{firebaseDirectory}"
            )
  end
end
